# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"



Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

#Misma clave para todas las máquinas
config.ssh.insert_key = false


 config.vm.define "client" do |cl|
  cl.vm.hostname = "client"
  cl.vm.box = "centos/7"
  cl.ssh.username = "vagrant"
  cl.vm.network "private_network", ip: "192.168.1.2"
 end

 config.vm.define "gateway" do |gw|
  gw.vm.hostname = "gateway"
  gw.vm.box = "centos/7"
  gw.ssh.username = "vagrant"
  gw.vm.network "private_network", ip: "192.168.1.10"
  gw.vm.network "private_network", ip: "192.168.2.10"
 end

 config.vm.define "load-balancer" do |lb|
  lb.vm.hostname = "load-balancer"
  lb.vm.box = "centos/7"
  lb.ssh.username = "vagrant"
  lb.vm.network "private_network", ip: "192.168.2.2"
  lb.vm.network "forwarded_port", guest: 8080, host: 8080 
 end

 
 config.vm.define "server1" do |s1|
  s1.vm.hostname = "server1"
  s1.vm.box = "centos/7"
  s1.vm.network "private_network", ip: "192.168.2.3"
  s1.ssh.username = "vagrant"
 end

 config.vm.define "server2" do |s2|
  s2.vm.hostname = "server2"
  s2.vm.box = "centos/7"
  s2.ssh.username = "vagrant"
  s2.vm.network "private_network", ip: "192.168.2.4"
  end
 
 

end
