# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.define :esgf do |esgf|
    esgf.vm.hostname = "esgf"
    esgf.vm.box = "centos/6"
    esgf.vm.network "private_network", ip: "172.28.128.3"

    esgf.vm.provision "file", source: "~/.vagrant.d/insecure_private_key", destination: "/tmp/id_rsa"
    esgf.vm.provision "shell", inline: "sudo bash -c 'mkdir /root/.ssh && ssh-keygen -y -f /tmp/id_rsa > /root/.ssh/authorized_keys && chmod 700 /root/.ssh && chmod 600 /root/.ssh/authorized_keys && sed -i \'s/#PermitRootLogin/PermitRootLogin/\' /etc/ssh/sshd_config && cp /tmp/id_rsa /root/.ssh/id_rsa' ; yum install -y git"

    esgf.vm.provider :virtualbox do |vb|
      vb.linked_clone = true
      vb.customize ["modifyvm", :id, "--memory", "1024"]
    end
  end

  config.vm.define :server1 do |server1|
    server1.vm.hostname = "server1"
    server1.vm.box = "centos/6"
    server1.vm.network "private_network", ip: "172.28.128.4"

    server1.vm.provider :virtualbox do |vb|
      vb.linked_clone = true
      vb.customize ["modifyvm", :id, "--memory", "1024"]
    end
  end

  config.vm.define :server2 do |server2|
    server2.vm.hostname = "server2"
    server2.vm.box = "centos/6"
    server2.vm.network "private_network", ip: "172.28.128.5"

    server2.vm.provider :virtualbox do |vb|
      vb.linked_clone = true
      vb.customize ["modifyvm", :id, "--memory", "1024"]
    end
  end

  config.vm.provision "shell", inline: "sudo yum install -y expect libselinux-python"
end
