# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

CLUSTER = ['load-balancer', 'server1', 'server2', 'dhcp']

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  #better performance with "linked clone" feature from VirtualBox
  config.vm.provider "virtualbox" do |v|
    v.linked_clone = true
    v.customize ["modifyvm", :id, "--nic2", "generic"]
    v.customize ["modifyvm", :id, "--nicgenericdrv2", "VDE"]
    v.customize ["modifyvm", :id, "--nicproperty2", "network=/tmp/switch1"]
  end

  config.vm.box = "centos/7"
  #Same key for all machines
  config.ssh.insert_key = false
  #config.vm.network "public_network"

  CLUSTER.each do |node|
    config.vm.define "#{node}" do |host|
      host.vm.hostname = "#{node}"
    end
  end
 # config.vm.proviser "ansible" do |ansible|
  #  ansible.playbook = "provision.yml"
   # ansible.groups = {
    #  "servers" => ["server1", "server2"]
  #  }
 # end

end
