# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

CLUSTER = ['dhcp', 'load-balancer', 'server1', 'server2']

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "centos/7"
  #Same key for all machines
  config.ssh.insert_key = false
  #config.vm.network "public_network"


  CLUSTER.each do |node|
    config.vm.define "#{node}" do |host|
      host.vm.hostname = "#{node}"
    end
    config.vm.provider "virtualbox" do |v|
      #better performance with "linked clone" feature from VirtualBox
      v.linked_clone = true
      #Configure switched private network
      v.customize ["modifyvm", :id, "--nic2", "generic"]
      v.customize ["modifyvm", :id, "--nicgenericdrv2", "VDE"]
      v.customize ["modifyvm", :id, "--nicproperty2", "network=/tmp/switch1"]
    end
  end

  config.vm.define "router" do |host|
    config.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--nic2", "generic"]
      v.customize ["modifyvm", :id, "--nicgenericdrv2", "VDE"]
      v.customize ["modifyvm", :id, "--nicproperty2", "network=/tmp/switch1"]
    end
    config.vm.network "private_network", ip: "192.168.0.2"
  end

  config.vm.define "client" do |host|
    config.vm.network "private_network", ip: "192.168.0.168"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provision.yml"
    ansible.groups = {
      "servers" => ["server[1:2]"]
    }
  end

end
