# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

CLUSTER = ['load-balancer', 'server1', 'server2']

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  #better performance with "linked clone" feature from VirtualBox
  config.vm.provider "virtualbox" do |v|
    v.linked_clone = true
  end

  config.vm.box = "centos/7"
  #Same key for all machines
  config.ssh.insert_key = false
 # config.vm.network "private_network", type: "dhcp"
  #config.vm.network "public_network"

  CLUSTER.each do |node|
    config.vm.define "#{node}" do |host|
      host.vm.provider "virtualbox" do |v|
        v.name = "#{node}"
        v.customize ["modifyvm","#{node}", "--nic2", "generic"]
        v.customize ["modifyvm","#{node}", "--nicgenericdrv2", "VDE"]
        v.customize ["modifyvm","#{node}", "--nicproperty2", "network=/tmp/switch1"]
      end
      host.vm.network "private_network", type: "dhcp"
      host.vm.hostname = "#{node}"

    end
  end

end
