# -*- mode: ruby -*-
# vi: set ft=ruby :

hosts = [{"name" => "proxy", "forwarded_port" => "9000"},
	{"name" => "hostA", "forwarded_port" => "9001"},
	{"name" => "hostB", "forwarded_port" => "9002"}]


limit = []
if ARGV[0] == "up"
	if ARGV.length > 1
		limit = ARGV.drop(1)
	else
		hosts.each { |x| limit.push(x["name"]) }
	end
end

Vagrant.configure("2") do |config|

	config.ssh.insert_key = false

	(0..(hosts.length - 1)).each do |n|
		host = hosts[n]
		config.vm.define host["name"] do |machine|
			machine.vm.hostname = host["name"]
			machine.vm.box = "centos/7"
			machine.vm.network "private_network", type: "dhcp"
			machine.vm.network "forwarded_port", host: host["forwarded_port"], guest: 8080

			machine.vm.provider :virtualbox do |vb|
				vb.linked_clone = true
				vb.customize ["modifyvm", :id, "--memory", "1024"]
			end

			if n == (limit.length - 1)
				machine.vm.provision :ansible do |ansible|
					ansible.limit = limit
					ansible.playbook = "provision.yml"
					ansible.groups = {
						"gateway" => ["proxy"],
						"tds" => ["hostA","hostB"],
						"tap" => ["hostA"],
						"test-simple" => ["proxy", "hostA"]
					}
				end
			end
		end
	end
end
