- name: Download derbydb
  become: False
  run_once: True
  local_action: get_url
  args:
    url: "{{ derby_url }}"
    dest: "{{ downloads }}"
    checksum: md5:{{ derby_md5 }}
  tags: [download, derby]

- name: Create {{ derby_home }}
  file: state=directory path={{ derby_home }}

- name: Unarchive derbydb
  unarchive:
    src: "{{ downloads }}/{{ derby_url | basename }}"
    dest: "{{ derby_home }}"
    extra_opts:
      - --strip-components=1

- name: Template derby.properties
  template: src=derby.properties.j2 dest={{ derby_home }}/derby.properties
