# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"



Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

#Misma clave para todas las máquinas
config.ssh.insert_key = false

 config.vm.define "load-balancer" do |host|
  host.vm.hostname = "load-balancer"
  host.vm.box = "centos/7"
  host.ssh.username = "vagrant"
  host.vm.network "private_network", ip: "192.168.10.1"
  host.vm.network "forwarded_port", guest: 8080, host: 8080 
 end

 
 config.vm.define "server1" do |host|
  host.vm.hostname = "server1"
  host.vm.box = "centos/7"
  host.vm.network "private_network", ip: "192.168.10.2"
  host.ssh.username = "vagrant"
 end

 config.vm.define "server2" do |host|
  host.vm.hostname = "server2"
  host.vm.box = "centos/7"
  host.ssh.username = "vagrant"
  host.vm.network "private_network", ip: "192.168.10.3"
  end
 
 config.vm.provision "ansible" do |ansible|
  ansible.playbook = "playbook.yml"
  ansible.ask_vault_pass = true
  ansible.groups = {
   "servers" => ["server1", "server2"]
  }
 end

end
