# -*- mode: ruby -*-
# vi: set ft=ruby :

hosts = [{"name" => "proxy", "ip" => "192.168.50.10", "forwarded_port" => "9000"},
	{"name" => "hostA", "ip" => "192.168.50.11", "forwarded_port" => "9001"},
	{"name" => "hostB", "ip" => "192.168.50.12", "forwarded_port" => "9002"}]

PROJECT_NAME = File.basename(Dir.getwd)

Vagrant.configure("2") do |config|

	hosts.each do |host|
		config.vm.define host["name"] do |node|
			node.vm.hostname = host["name"]
			node.vm.box = "centos/7"
			node.vm.network "private_network", ip: host["ip"]
			node.vm.network "forwarded_port", host: host["forwarded_port"], guest: 8080
			node.ssh.insert_key = false

			node.vm.provision "file", source: "selinux", destination: "/tmp/selinux"
			node.vm.provision "shell", inline: "cp -f /tmp/selinux /etc/sysconfig/selinux"

			node.vm.provider :virtualbox do |vb|
				vb.linked_clone = true
				vb.customize ["modifyvm", :id,"--groups", "/"+PROJECT_NAME,"--memory", "1024"]
			end
		end
	end
end
