# -*- mode: ruby -*-
# vi: set ft=ruby :

hosts = [{"name" => "proxy", "ip" => "192.168.50.10", "forwarded_port" => "9000"},
	{"name" => "hostA", "ip" => "192.168.50.11", "forwarded_port" => "9001"},
	{"name" => "hostB", "ip" => "192.168.50.12", "forwarded_port" => "9002"}]

Vagrant.configure("2") do |config|

	hosts.each do |host|
		config.vm.define host["name"] do |node|
			node.vm.hostname = host["name"]
			node.vm.box = "centos/7"
			node.vm.network "private_network", ip: host["ip"]
			node.vm.network "forwarded_port", host: host["forwarded_port"], guest: 8080
			node.ssh.insert_key = false

			node.vm.provider :virtualbox do |vb|
				vb.linked_clone = true
				vb.customize ["modifyvm", :id, "--memory", "1024"]
			end
		end
	end
end
