#!/bin/bash

# Last slash is mandatory
root=/oceano/gmeteo/WORK/zequi/DATASETS/cmip5-esm-subset/data/

ncmls=/oceano/gmeteo/WORK/zequi/DATASETS/cmip5-esm-subset/ncmls/

# NcMLs
ncmlify --project cmip5 --root "$root" --ncmls "$ncmls"
#csvify --project cmip5 "$root" | ncml --ncmls "$ncmls"

# Catalog
catalog --name 'CMIP5-ESM-Subset' --ncml "$ncmls" --data "$root" > catalogs/cmip5-esm-subset.xml
