#!/bin/bash

# Last slash is mandatory
root=/oceano/gmeteo/WORK/zequi/DATASETS/synda-demo/data/

ncmls=/oceano/gmeteo/WORK/zequi/DATASETS/synda-demo/ncmls/

# NcMLs
ncmlify --project cmip5 --root "$root" --ncmls "$ncmls"

# Catalog
catalog --name 'DemoDataset' --ncml "$ncmls" --data "$root" > catalogs/demo.xml
