- name: Deploy load balancers
  hosts: lbs
  vars:
    httpd_root: /etc/httpd
    httpd_conf_file: /etc/httpd/conf/esgf-httpd.conf
    httpd_version: 2.2.15
  roles:
    - role: load-balancer
      lb_type: modproxy
  pre_tasks:
    # spock is supposed to have an ESGF node installed but lxc container is empty
    - name: Install httpd in lxd container
      include_role: name=httpd-centos7
      when: "'spock' == inventory_hostname"

    - name: Copy esgf-httpd.conf with /thredds disabled
      copy: src=esgf-httpd.conf dest=/etc/httpd/conf/esgf-httpd.conf

- name: Deploy workers
  hosts: workers
  vars:
    jdk_root: "{{ ansible_env.HOME }}/deployment/jdk"
    tomcat_home: "{{ ansible_env.HOME }}/deployment/tomcat"
    tds_root_catalog: catalog.xml
  roles:
    - role: jdk-source
    - role: tomcat-source
    - role: worker
  tasks:
    - name: Copy catalogs
      copy: src=catalogs dest={{ tomcat_base }}/{{ item.name }}/content/thredds
      with_items: "{{ tomcats }}"
      tags: catalogs

    - import_tasks: ../../utils/restart.yml
      tags: catalogs, restart

- name: Restart load balancer
  hosts: lbs
  tasks:
    - name: Restart httpd
      service: name=httpd state=restarted
      tags: restart
